-- Generated by HyprMod

-- Settings
hl.config({
    cursor = {
        hide_on_key_press = true,
        inactive_timeout = 5.0,
    },
    general = {
        border_size = 3,
        gaps_out = 8,
        resize_on_border = true,
        snap = {
            enabled = true,
        },
    },
    gestures = {
        workspace_swipe_forever = true,
        workspace_swipe_touch = true,
    },
    misc = {
        disable_splash_rendering = true,
        vrr = 0,
    },
})
